services:
  immich-network-storage-api:
    build:
      context: /omv/apps-compose/immich-network-storage/repo
      dockerfile: Dockerfile
      network: host
    container_name: immich-network-storage-api
    user: 82:82
    env_file:
      - .env
    ports:
      - "22832:${SERVER_PORT_SFTP}" # SFTP
      - "19000:${SERVER_PORT_WEBDAV}" # WebDAV
    volumes:
      - ${SERVER_PATH_APPDATA}:/data
      - ${SERVER_PATH_APPCONFIG}:/config
      - ${SERVER_PATH_IMMICH_UPLOADS}:/immich/data
      - ${SERVER_PATH_LOGS}:/logs
    restart: unless-stopped
