services:
  immich-file-bridge:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: immich-file-bridge
    user: 82:82
    env_file:
      - .env
    ports:
      - "22832:${SERVER_PROTOCOL_PORTS_SFTP}" # SFTP
      - "19000:${SERVER_PROTOCOL_PORTS_WEBDAV}" # WebDAV
    volumes:
      - ${SERVER_PATH_APPDATA}:/data
      - ${SERVER_PATH_APPCONFIG}:/config
      - ${SERVER_PATH_IMMICH_UPLOADS}:/immich/data
      - ${SERVER_PATH_LOGS}:/logs
    restart: unless-stopped
