services:
  immich-file-bridge:
    develop:
      watch:
        - action: rebuild
          path: .
    user: 82:82
    command: >
      ts-node-dev --inspect=0.0.0.0:9229 src/server.ts
    ports:
      - "9229:9229" # Development Port
      - "22832:${SERVER_PORT_SFTP}" # SFTP
      - "19000:${SERVER_PORT_WEBDAV}" # WebDAV
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      NODE_ENV: development
